### PR TITLE
add leg.price

### PR DESCRIPTION
**Pull request by juliuste**
Implements #45

### CODE REVIEW

**Comment by derhuerst** [comment]
I think we should use an array of prices. A single price, exposed as `.price`, seems a bit too limited.

**Comment by juliuste** [comment]
I think `journey.price` and `leg.price` should have the same structure. We can talk about your proposal in FPTF@2, but for now, my PR is in line with `journey.price@1`, which makes the most sense IMHO.

**Comment by derhuerst** [comment]
Makes sense.

**Comment by juliuste** [comment]
@derhuerst feel free to open an issue for [your proposal from above](https://github.com/public-transport/friendly-public-transport-format/pull/47#issuecomment-416050898)

**Pull request merged**
