### PR TITLE
specify cancelled departures/arrivals

### LINKED ISSUE #27: canceled trips & departures/arrivals
What should we do with them? Omit them from the results? Mark them as canceled?

see also derhuerst/vbb-rest#19

### PR DESCRIPTION
**Pull request by derhuerst**
closes #27

### CODE REVIEW

**Comment by juliuste** [comment]
`canceled` should be required, right?

**Comment by derhuerst** [comment]
Should it? For now, I've only assigned it if the trips is actually canceled. Don't you think this is sufficient? Is making `canceled` required worth raising the barrier to use FPTF by a little?

**Comment by juliuste** [comment]
You're right, since this is about `fptf@1` and it would be a breaking change, making it required here doesn't make sense. For `fptf@2` [we agreed that it should be required](https://github.com/public-transport/friendly-public-transport-format/issues/27#issuecomment-373914205).

**Comment by derhuerst** [comment]
Note: This is actually a breaking change and should be PRed against `next`.

**Pull request closed without merging**
